export const jobDescription = "We are seeking a highly skilled and talented UI/UX Designer to join our dynamic team. The successful candidate will be responsible for creating visually appealing and user-friendly interfaces for our digital products (website & learning experience) ensuring a seamless and engaging user experience."

export const requirementData ='Bachelor degree in Graphic Design, Interaction Design, or related field.Proven experience as a UI/UX Designer, preferably in a similar industry or domain.Strong portfolio showcasing a wide range of UI/UX design projects, including wireframe, prototypes, and visual designs.Proficient in design tools such as Sketch, Figma, Adobe XD, or similar.Proven expertise in user-centered design principles, usability, and accessibility best practices.Strong visual design skills, including color theory, typography, and layout.Excellent communication and collaboration skills, with the ability to work effectively in cross-functional teams.'

export const responsibilitesData =
  'Collaborate with cross-functional teams, including product managers, developers, and other stakeholders, to understand project requirements and translate them into intuitive and visually appealing UI/UX designs.Create wireframes, prototypes, and mockups to demonstrate user interactions and functionality, and iterate on designs based on feedback and user testing results.Conduct user research and usability testing to gather feedback and insights for iterative design improvements.Develop and maintain design guidelines, style guides, and design systems to ensure consistency across all digital products.Stay updated on industry trends, best practices, and emerging technologies related to UI/UX design, and incorporate them into design processes to drive innovation and improve user experiences.Work closely with developers to ensure proper implementation of designs, and provide design assets and specifications for development.Collaborate with marketing and branding teams to ensure consistent branding and visual design across all touchpoints.Act as a user advocate, constantly advocating for the needs and preferences of end users in design decisions.Conduct design QA and design critic sessions across the product.'

export const aboutCompany =
  'Founded in 2011 and trusted by companies across 70 countries and more, KnowledgeHut is the skills solutions provider that organizations and individuals the world over count on to innovate faster and create progress.We help technologists master their craft and take control of their careers.We empower businesses everywhere to build adaptable teams, speed up release cycles and become scalable, reliable, and secure.Our mission to democratize technology skills is what drives us, and our values are at the helm of how we work together.We thrive in an environment with creativity around every corner, challenges that keep us on our toes, and peers who inspire us to be the best we can be.';
export const companyWebsite = 'https://www.knowledgehut.com/';
export const headquarter =
  'Vaishnavi Tech Park, Sarjapur Main Rd, Bellandur, Bengaluru, Karnataka 560103';
